
- name: Connection
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: cisco
    ansible_password: cisco

  tasks:
    - name: Run Show version
      ios_command:
        commands: show version
